// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace BubbleStart.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class day23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(day23));
        
        string IMigrationMetadata.Id
        {
            get { return "201904041546485_day23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
