// <auto-generated />
namespace BubbleStart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _12173 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12173));
        
        string IMigrationMetadata.Id
        {
            get { return "201912171709207_12173"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
