// <auto-generated />
namespace BubbleStart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _1220 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1220));
        
        string IMigrationMetadata.Id
        {
            get { return "201912202111232_1220"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
