// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace BubbleStart.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _421 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_421));
        
        string IMigrationMetadata.Id
        {
            get { return "201904210157028_421"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
