// <auto-generated />
namespace BubbleStart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class boost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(boost));
        
        string IMigrationMetadata.Id
        {
            get { return "202004010625255_boost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
