// <auto-generated />
namespace BubbleStart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixes2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixes2));
        
        string IMigrationMetadata.Id
        {
            get { return "202212191026419_fixes2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
