// <auto-generated />
namespace BubbleStart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Second_store : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Second_store));
        
        string IMigrationMetadata.Id
        {
            get { return "202410082223514_Second_store"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
